### ISSUE TITLE
[Security] Unclear behavior

### ISSUE THREAD

**Issue by retyui** [fullstorydev/fullstory-babel-plugin-react-native#4]
What was the reason to hide the implementation? What actually this plugin do?

[lib/index.js](https://github.com/fullstorydev/fullstory-babel-plugin-react-native/blob/master/lib/index.js)

**Comment by JoshMiers-FS** [comment]
Hey there!
Thanks for reaching out and filing an issue with us here on Github. Our react native babel plugin is currently in private beta which is why you may find the documentation a bit lacking here on GitHub. If you’re interested in gaining access to the private beta, please email mobile-support@fullstory.com and we’ll follow up with next steps. While we wish we could grant everyone access to the beta program, please bear in mind that we’re evaluating each request on a case-by-case basis and admission into the beta is not guaranteed.

Once we’re out of private beta and access to our react native babel plugin is more widely available, we will update our documentation **as well as post the non-obfuscated source code**. Sorry for any confusion this has caused and thank you for your patience while we work to make this plugin great for the entire community.
